/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyDataCreateNestedManyWithoutUsersInput } from "./CompanyDataCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserCommunicationCreateNestedManyWithoutUsersInput } from "./UserCommunicationCreateNestedManyWithoutUsersInput";
import { UserRequestCreateNestedManyWithoutUsersInput } from "./UserRequestCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyDataCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CompanyDataCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CompanyDataCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  companyDataItems?: CompanyDataCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserCommunicationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserCommunicationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserCommunicationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userCommunications?: UserCommunicationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => UserRequestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserRequestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserRequestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userRequests?: UserRequestCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
