/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyDataUpdateManyWithoutUsersInput } from "./CompanyDataUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserCommunicationUpdateManyWithoutUsersInput } from "./UserCommunicationUpdateManyWithoutUsersInput";
import { UserRequestUpdateManyWithoutUsersInput } from "./UserRequestUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyDataUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CompanyDataUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CompanyDataUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  companyDataItems?: CompanyDataUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserCommunicationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserCommunicationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserCommunicationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userCommunications?: UserCommunicationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => UserRequestUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserRequestUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserRequestUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userRequests?: UserRequestUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
