/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Company } from "./Company";
import { CompanyCountArgs } from "./CompanyCountArgs";
import { CompanyFindManyArgs } from "./CompanyFindManyArgs";
import { CompanyFindUniqueArgs } from "./CompanyFindUniqueArgs";
import { CreateCompanyArgs } from "./CreateCompanyArgs";
import { UpdateCompanyArgs } from "./UpdateCompanyArgs";
import { DeleteCompanyArgs } from "./DeleteCompanyArgs";
import { CompanyDataFindManyArgs } from "../../companyData/base/CompanyDataFindManyArgs";
import { CompanyData } from "../../companyData/base/CompanyData";
import { PrivacyAgreementFindManyArgs } from "../../privacyAgreement/base/PrivacyAgreementFindManyArgs";
import { PrivacyAgreement } from "../../privacyAgreement/base/PrivacyAgreement";
import { UserCommunicationFindManyArgs } from "../../userCommunication/base/UserCommunicationFindManyArgs";
import { UserCommunication } from "../../userCommunication/base/UserCommunication";
import { UserRequestFindManyArgs } from "../../userRequest/base/UserRequestFindManyArgs";
import { UserRequest } from "../../userRequest/base/UserRequest";
import { CompanyService } from "../company.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Company)
export class CompanyResolverBase {
  constructor(
    protected readonly service: CompanyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "read",
    possession: "any",
  })
  async _companiesMeta(
    @graphql.Args() args: CompanyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Company])
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "read",
    possession: "any",
  })
  async companies(
    @graphql.Args() args: CompanyFindManyArgs
  ): Promise<Company[]> {
    return this.service.companies(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Company, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "read",
    possession: "own",
  })
  async company(
    @graphql.Args() args: CompanyFindUniqueArgs
  ): Promise<Company | null> {
    const result = await this.service.company(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Company)
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "create",
    possession: "any",
  })
  async createCompany(
    @graphql.Args() args: CreateCompanyArgs
  ): Promise<Company> {
    return await this.service.createCompany({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Company)
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "update",
    possession: "any",
  })
  async updateCompany(
    @graphql.Args() args: UpdateCompanyArgs
  ): Promise<Company | null> {
    try {
      return await this.service.updateCompany({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Company)
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "delete",
    possession: "any",
  })
  async deleteCompany(
    @graphql.Args() args: DeleteCompanyArgs
  ): Promise<Company | null> {
    try {
      return await this.service.deleteCompany(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [CompanyData], { name: "companyDataItems" })
  @nestAccessControl.UseRoles({
    resource: "CompanyData",
    action: "read",
    possession: "any",
  })
  async findCompanyDataItems(
    @graphql.Parent() parent: Company,
    @graphql.Args() args: CompanyDataFindManyArgs
  ): Promise<CompanyData[]> {
    const results = await this.service.findCompanyDataItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [PrivacyAgreement], { name: "privacyAgreements" })
  @nestAccessControl.UseRoles({
    resource: "PrivacyAgreement",
    action: "read",
    possession: "any",
  })
  async findPrivacyAgreements(
    @graphql.Parent() parent: Company,
    @graphql.Args() args: PrivacyAgreementFindManyArgs
  ): Promise<PrivacyAgreement[]> {
    const results = await this.service.findPrivacyAgreements(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [UserCommunication], {
    name: "userCommunications",
  })
  @nestAccessControl.UseRoles({
    resource: "UserCommunication",
    action: "read",
    possession: "any",
  })
  async findUserCommunications(
    @graphql.Parent() parent: Company,
    @graphql.Args() args: UserCommunicationFindManyArgs
  ): Promise<UserCommunication[]> {
    const results = await this.service.findUserCommunications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [UserRequest], { name: "userRequests" })
  @nestAccessControl.UseRoles({
    resource: "UserRequest",
    action: "read",
    possession: "any",
  })
  async findUserRequests(
    @graphql.Parent() parent: Company,
    @graphql.Args() args: UserRequestFindManyArgs
  ): Promise<UserRequest[]> {
    const results = await this.service.findUserRequests(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
