/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyDataListRelationFilter } from "../../companyData/base/CompanyDataListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { PrivacyAgreementListRelationFilter } from "../../privacyAgreement/base/PrivacyAgreementListRelationFilter";
import { UserCommunicationListRelationFilter } from "../../userCommunication/base/UserCommunicationListRelationFilter";
import { UserRequestListRelationFilter } from "../../userRequest/base/UserRequestListRelationFilter";

@InputType()
class CompanyWhereInput {
  @ApiProperty({
    required: false,
    type: () => CompanyDataListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CompanyDataListRelationFilter)
  @IsOptional()
  @Field(() => CompanyDataListRelationFilter, {
    nullable: true,
  })
  companyDataItems?: CompanyDataListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  contactInfo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PrivacyAgreementListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PrivacyAgreementListRelationFilter)
  @IsOptional()
  @Field(() => PrivacyAgreementListRelationFilter, {
    nullable: true,
  })
  privacyAgreements?: PrivacyAgreementListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserCommunicationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserCommunicationListRelationFilter)
  @IsOptional()
  @Field(() => UserCommunicationListRelationFilter, {
    nullable: true,
  })
  userCommunications?: UserCommunicationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserRequestListRelationFilter)
  @IsOptional()
  @Field(() => UserRequestListRelationFilter, {
    nullable: true,
  })
  userRequests?: UserRequestListRelationFilter;
}

export { CompanyWhereInput as CompanyWhereInput };
