/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyDataUpdateManyWithoutCompaniesInput } from "./CompanyDataUpdateManyWithoutCompaniesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { PrivacyAgreementUpdateManyWithoutCompaniesInput } from "./PrivacyAgreementUpdateManyWithoutCompaniesInput";
import { UserCommunicationUpdateManyWithoutCompaniesInput } from "./UserCommunicationUpdateManyWithoutCompaniesInput";
import { UserRequestUpdateManyWithoutCompaniesInput } from "./UserRequestUpdateManyWithoutCompaniesInput";

@InputType()
class CompanyUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyDataUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => CompanyDataUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => CompanyDataUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  companyDataItems?: CompanyDataUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactInfo?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PrivacyAgreementUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => PrivacyAgreementUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => PrivacyAgreementUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  privacyAgreements?: PrivacyAgreementUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => UserCommunicationUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => UserCommunicationUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => UserCommunicationUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  userCommunications?: UserCommunicationUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => UserRequestUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => UserRequestUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => UserRequestUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  userRequests?: UserRequestUpdateManyWithoutCompaniesInput;
}

export { CompanyUpdateInput as CompanyUpdateInput };
