/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserRequest } from "./UserRequest";
import { UserRequestCountArgs } from "./UserRequestCountArgs";
import { UserRequestFindManyArgs } from "./UserRequestFindManyArgs";
import { UserRequestFindUniqueArgs } from "./UserRequestFindUniqueArgs";
import { CreateUserRequestArgs } from "./CreateUserRequestArgs";
import { UpdateUserRequestArgs } from "./UpdateUserRequestArgs";
import { DeleteUserRequestArgs } from "./DeleteUserRequestArgs";
import { Company } from "../../company/base/Company";
import { User } from "../../user/base/User";
import { UserRequestService } from "../userRequest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserRequest)
export class UserRequestResolverBase {
  constructor(
    protected readonly service: UserRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserRequest",
    action: "read",
    possession: "any",
  })
  async _userRequestsMeta(
    @graphql.Args() args: UserRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserRequest])
  @nestAccessControl.UseRoles({
    resource: "UserRequest",
    action: "read",
    possession: "any",
  })
  async userRequests(
    @graphql.Args() args: UserRequestFindManyArgs
  ): Promise<UserRequest[]> {
    return this.service.userRequests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserRequest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserRequest",
    action: "read",
    possession: "own",
  })
  async userRequest(
    @graphql.Args() args: UserRequestFindUniqueArgs
  ): Promise<UserRequest | null> {
    const result = await this.service.userRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserRequest)
  @nestAccessControl.UseRoles({
    resource: "UserRequest",
    action: "create",
    possession: "any",
  })
  async createUserRequest(
    @graphql.Args() args: CreateUserRequestArgs
  ): Promise<UserRequest> {
    return await this.service.createUserRequest({
      ...args,
      data: {
        ...args.data,

        company: args.data.company
          ? {
              connect: args.data.company,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserRequest)
  @nestAccessControl.UseRoles({
    resource: "UserRequest",
    action: "update",
    possession: "any",
  })
  async updateUserRequest(
    @graphql.Args() args: UpdateUserRequestArgs
  ): Promise<UserRequest | null> {
    try {
      return await this.service.updateUserRequest({
        ...args,
        data: {
          ...args.data,

          company: args.data.company
            ? {
                connect: args.data.company,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserRequest)
  @nestAccessControl.UseRoles({
    resource: "UserRequest",
    action: "delete",
    possession: "any",
  })
  async deleteUserRequest(
    @graphql.Args() args: DeleteUserRequestArgs
  ): Promise<UserRequest | null> {
    try {
      return await this.service.deleteUserRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Company, {
    nullable: true,
    name: "company",
  })
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "read",
    possession: "any",
  })
  async getCompany(
    @graphql.Parent() parent: UserRequest
  ): Promise<Company | null> {
    const result = await this.service.getCompany(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: UserRequest): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
