/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserCommunication } from "./UserCommunication";
import { UserCommunicationCountArgs } from "./UserCommunicationCountArgs";
import { UserCommunicationFindManyArgs } from "./UserCommunicationFindManyArgs";
import { UserCommunicationFindUniqueArgs } from "./UserCommunicationFindUniqueArgs";
import { CreateUserCommunicationArgs } from "./CreateUserCommunicationArgs";
import { UpdateUserCommunicationArgs } from "./UpdateUserCommunicationArgs";
import { DeleteUserCommunicationArgs } from "./DeleteUserCommunicationArgs";
import { Company } from "../../company/base/Company";
import { User } from "../../user/base/User";
import { UserCommunicationService } from "../userCommunication.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserCommunication)
export class UserCommunicationResolverBase {
  constructor(
    protected readonly service: UserCommunicationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserCommunication",
    action: "read",
    possession: "any",
  })
  async _userCommunicationsMeta(
    @graphql.Args() args: UserCommunicationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserCommunication])
  @nestAccessControl.UseRoles({
    resource: "UserCommunication",
    action: "read",
    possession: "any",
  })
  async userCommunications(
    @graphql.Args() args: UserCommunicationFindManyArgs
  ): Promise<UserCommunication[]> {
    return this.service.userCommunications(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserCommunication, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserCommunication",
    action: "read",
    possession: "own",
  })
  async userCommunication(
    @graphql.Args() args: UserCommunicationFindUniqueArgs
  ): Promise<UserCommunication | null> {
    const result = await this.service.userCommunication(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserCommunication)
  @nestAccessControl.UseRoles({
    resource: "UserCommunication",
    action: "create",
    possession: "any",
  })
  async createUserCommunication(
    @graphql.Args() args: CreateUserCommunicationArgs
  ): Promise<UserCommunication> {
    return await this.service.createUserCommunication({
      ...args,
      data: {
        ...args.data,

        company: args.data.company
          ? {
              connect: args.data.company,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserCommunication)
  @nestAccessControl.UseRoles({
    resource: "UserCommunication",
    action: "update",
    possession: "any",
  })
  async updateUserCommunication(
    @graphql.Args() args: UpdateUserCommunicationArgs
  ): Promise<UserCommunication | null> {
    try {
      return await this.service.updateUserCommunication({
        ...args,
        data: {
          ...args.data,

          company: args.data.company
            ? {
                connect: args.data.company,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserCommunication)
  @nestAccessControl.UseRoles({
    resource: "UserCommunication",
    action: "delete",
    possession: "any",
  })
  async deleteUserCommunication(
    @graphql.Args() args: DeleteUserCommunicationArgs
  ): Promise<UserCommunication | null> {
    try {
      return await this.service.deleteUserCommunication(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Company, {
    nullable: true,
    name: "company",
  })
  @nestAccessControl.UseRoles({
    resource: "Company",
    action: "read",
    possession: "any",
  })
  async getCompany(
    @graphql.Parent() parent: UserCommunication
  ): Promise<Company | null> {
    const result = await this.service.getCompany(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: UserCommunication
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
